version: "3.8"
services:
  app:
    pull_policy: build
    build:
      context: ./app
      target: prod
    environment:
      - NODE_ENV=production
    container_name: icf_tech_react_test_fe
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - ./app:/app
      - /app/node_modules
